#pragma once

////////////////////////////////////////////////////////////////
// Includes

#include "Gugu/Common.h"

////////////////////////////////////////////////////////////////
// Macros

#define GUGU_AUDIOPLAYER_VERSION_MAJOR 0
#define GUGU_AUDIOPLAYER_VERSION_MINOR 4
#define GUGU_AUDIOPLAYER_VERSION_PATCH 0
#define GUGU_AUDIOPLAYER_VERSION_IS_DEV true
#define GUGU_AUDIOPLAYER_VERSION_IS_PRE_RELEASE false
#define GUGU_AUDIOPLAYER_VERSION_IS_POST_RELEASE false

#define GUGU_AUDIOPLAYER_VERSION_NUMBER GUGU_STRINGIZE(GUGU_AUDIOPLAYER_VERSION_MAJOR) "." GUGU_STRINGIZE(GUGU_AUDIOPLAYER_VERSION_MINOR) "." GUGU_STRINGIZE(GUGU_AUDIOPLAYER_VERSION_PATCH)

#if GUGU_AUDIOPLAYER_VERSION_IS_DEV
#define GUGU_AUDIOPLAYER_VERSION GUGU_AUDIOPLAYER_VERSION_NUMBER "-dev"
#elif GUGU_AUDIOPLAYER_VERSION_IS_PRE_RELEASE
#define GUGU_AUDIOPLAYER_VERSION GUGU_AUDIOPLAYER_VERSION_NUMBER "-rc"
#elif GUGU_AUDIOPLAYER_VERSION_IS_POST_RELEASE
#define GUGU_AUDIOPLAYER_VERSION GUGU_AUDIOPLAYER_VERSION_NUMBER "-post"
#else
#define GUGU_AUDIOPLAYER_VERSION GUGU_AUDIOPLAYER_VERSION_NUMBER
#endif
